### ISSUE TITLE
Support DeploymentConfiguration of OpenShift

### ISSUE THREAD

**Issue by tobru** [appscode/stash#161] opened 2017-08-29 17:44 UTC
Would it be possible for stash to support the `DeploymentConfiguration` object of OpenShift? It's very similar to the `Deployment` object of Kubernetes.

**Comment by tamalsaha** [comment] 2017-08-31 00:16
Thanks for filing this issue. I am not familiar with OpenShift specific extensions. If you are interested in contributing pr, we will be happy to take a look. Some questions I have:
- Is this a CRD? We don't support TPRs any more.
- Is there an official GO library that defines this type that we can use here?

**Comment by tamalsaha** [comment] 2017-10-10 06:21
@tobru , now that we have released 0.5.0, we can potentially look at supporting this. I wonder if you can answer the questions above? If you are not interested in this, can you close this issue?

**Comment by tobru** [comment] 2017-10-10 08:47
@tamalsaha sorry for not getting back to you earlier. I'm still interested in support for the `DeplymentConfiguration` object.

> If you are interested in contributing pr, we will be happy to take a look.

I'm not a GO developer, so that would be (too) hard for me at the moment.

> Is this a CRD? We don't support TPRs any more.

No, it's a "core" object of OpenShift.

> Is there an official GO library that defines this type that we can use here?

Probably yes, but I'm not sure about it. The sourcecode of OpenShift lies here: https://github.com/openshift/origin. And there is an extraction of the OpenAPI specification here: https://github.com/garethr/openshift-json-schema/tree/master/v3.6.0. And the API documentation here: https://docs.openshift.org/latest/rest_api/oapi/v1.DeploymentConfig.html

**Comment by tamalsaha** [comment] 2018-02-16 16:07
Type Definition: https://github.com/openshift/origin/blob/v3.7.1/pkg/apps/apis/apps/v1/types.go#L27

Client: https://github.com/openshift/client-go/blob/master/apps/clientset/versioned/typed/apps/v1/deploymentconfig.go#L15

**Comment by tamalsaha** [comment] 2018-02-20 04:31
https://github.com/minishift/minishift

**Comment by tamalsaha** [comment] 2018-03-21 11:12
Docs:
- https://docs.openshift.com/container-platform/3.9/dev_guide/deployments/how_deployments_work.html
- https://docs.openshift.com/container-platform/3.9/architecture/core_concepts/deployments.html#deployments-and-deployment-configurations
- https://docs.openshift.com/container-platform/3.9/rest_api/apis-apps.openshift.io/v1.DeploymentConfig.html

**Comment by pierreozoux** [comment] 2018-08-09 13:48
Hello @tamalsaha we just made a snapshot/recovery run in OpenShift, using replication-controller.
Of course, the issue is that then we have a new RC for each version. And we are interested in having this issue resolved as well :)

But I wanted to say, that the project is already usable in OpenShift, and we are really happy! Thanks!

**Comment by tamalsaha** [comment] 2018-08-15 17:33
Thanks @pierreozoux . We are looking to support DeploymentConfig. Did you face any issue related to SCC in OpenShift?

**Comment by pierreozoux** [comment] 2018-08-16 14:35
@tamalsaha no, no issue so far.

**Comment by tamalsaha** [comment] 2019-03-22 11:49
This requires openshift 3.9.0 . Thanks to instructions from https://github.com/minishift/minishift/issues/2222, we can use minishift to test this locally. To test locally, download `minishift` from http://artifacts.ci.centos.org/minishift/minishift/master/latest/linux-amd64/ and move it to `/usr/local/bin` folder.

Then run 
```
minishift delete --force

minishift addons install --defaults
minishift addons enable admin-user
minishift start --vm-driver=virtualbox
```

Open web UI and login using user: admin , pass: <anything> (minishift accepts anything as password)

Copy the oc login url from web ui and paste to terminal and use it.

**Comment by tamalsaha** [comment] 2019-03-28 06:36
Check using discovery api if `apps.openshift.io/v1, DeploymentConfig`

https://github.com/appscode/voyager/blob/master/pkg/operator/servicemonitors.go#L18

**Comment by tamalsaha** [comment] 2019-03-28 06:38
https://github.com/kmodules/openshift/tree/master/apis/apps/v1

**Closed** 2019-04-02 13:34 UTC
Labels: api/v1beta1, enhancement
